image: Visual Studio 2019

before_build:
- nuget restore
- dotnet tool install -g Codecov.Tool --add-source "https://ci.appveyor.com/nuget/codecov-exe" --version "1.10.0-unstable0001"
- codecov -f "CalculatorCodeCoverage.xml"
build:
  project: Calculator.sln
  verbosity: minimal

