image: Visual Studio 2019
codecov:
  disable_default_path_fixes: false

before_build:
- nuget restore
- dotnet tool install --global Codecov.Tool --version 1.12.3
- codecov -f "CalculatorCodeCoverage.xml"
build:
  project: Calculator.sln
  verbosity: minimal

